### ISSUE TITLE
imexam radial profiles - error in radius value on x-axis

### ISSUE THREAD

**Issue by mackjenn** [spacetelescope/imexam#134]
http://imexam.readthedocs.io/en/latest/imexam/examples.html#example-2

Trying out Example 2, but find that the radial profile in python does not match the one from pyraf.  The radial profiles are helpful diagnostics for evaluating the quality of the PSFs.

Here is a comparison of the same star used in the example. 
![imexam_ex2](https://user-images.githubusercontent.com/28714829/38271745-471a62ca-3755-11e8-8d99-a2910df1e01e.png)
The flux values match up nicely (see yellow lines), but the radius values seem to be offset from where they should be. Could there be an error in calculating the distance from the star centroid position?  For example, the second point from the top needs to move left in the python version.  I'm not sure if all radius values are off, or just a subset. 

Here is a second example, which shows the effect much more clearly.  

![imexam_uvis_example](https://user-images.githubusercontent.com/28714829/38271412-685f5248-3754-11e8-9062-2a7b0af59d53.png)

**Comment by hcferguson** [comment]
My guess is that the centering isn't the same.

**Comment by mackjenn** [comment]
In the first plot, 
python(x,y)= (462.44, 377.04)
pyraf(x,y)   = (463.38, 378.08)   
In the 2nd plot
python(x,y)= (1864.32, 1093.86)
pyraf(x,y)   = (1865.28, 1094.86)   
so aside from (-1,-1) difference in convention, the center values are nearly identical.

**Comment by sosey** [comment]
perhaps local sky subtraction?  Will you send me the parameters you used for both versions?

**Comment by sosey** [comment]
hey @mackjenn, do me a favor and install imexam from the current master and try again? There's lots of updates there, and I'm pushing more this week getting ready for a new release. 

from a conda environment:
```
conda unintall imexam  # unless it says <pip> then pip uninstall
pip install git+https://github.com/spacetelescope/imexam
```

**Comment by mackjenn** [comment]
Sure, I'll do an update. 
My parameters are below.  

One question is whether the python parameter 'skyrad' and the pyraf parameter 'buffer' are the same. I think not.  I'm assuming skyrad is from the star center, whereas, buffer= skyradius-aperture_radius.

For example, skyrad=15 is the same as buffer=10 for an aperture radius =5.   (TRUE?)

-----Aperture Photometry Comparison-----

'skyrad': [15, 'Distance to start sky annulus is pixels']
x              y              radius         flux           mag(zpt=25.00)        sky             fwhm
1864.32        1093.86        5              16762.87       14.44         83.97          2.18      
rimexam buffer=10  [Background buffer width]
1865.28       1094.86         5.00         16937.           14.43         82.31          1.77  

----PARAMETERS---
viewer.rimexam()
'background': [False, 'Subtract background? [bool]'],
'getdata': [False, 'print the plotted data values'],
'fittype': ['Gaussian2D', 'Profile type to fit (Gaussian2D)'],
'center': [True, 'Solve for center using 2d Gaussian? [bool]'],
'rplot': [8.0, 'Plotting radius in pixels'],
'function': ['radial_profile'],
'pointmode': [True, 'plot points instead of lines? [bool]'],
'fitplot': [False, 'Overplot profile fit?'],
'pixels': [True, 'Plot all pixels at each radius? (False bins the data)'],
'skyrad': [15.0, 'Background inner radius in pixels, from center of object'],
'width': [5.0, 'Background annulus width in pixels'],
'magzero': [25.0, 'magnitude zero point'],

--> lpar rimexam
     (fitplot = yes)            Overplot profile fit?
     (fittype = "moffat")       Profile type to fit
      (center = yes)            Center object in aperture?
  (background = yes)            Fit and subtract background?
      (radius = 5.0)            Object radius
      (buffer = 10.0)           Background buffer width
       (width = 5.0)            Background width
  (iterations = 1)              Number of radius adjustment iterations
      (xorder = 0)              Background x order
      (yorder = 0)              Background y order
     (magzero = 25.0)           Magnitude zero point
        (beta = INDEF)          Moffat beta parameter
       (rplot = 8.0)            Plotting radius

**Comment by philhodge** [comment]
@mackjenn I think your interpretation is correct.  The help file for iraf imexam is almost incoherent with regard to `buffer`:  "Buffer distance from object aperture of background  annulus  for aperture sums and radial profile plots."

**Comment by mackjenn** [comment]
I updated to imexam-0.8.1.dev344, but see the same behavior.
I will say the new aperture photometry graphic is great!! 

Also, I realize that I forgot to set background=True for the radial plot, but that doesn't change the results. (It simply offsets all the points by a small constant value on the y-axis). 

Thanks for having a look at this, Megan!  😃

**Comment by sosey** [comment]
**RE: skyrad for this package:**

The `imexam` radial profile parameters:
```
{'background': [False, 'Subtract background? [bool]'],
 'center': [True, 'Solve for center using 2d Gaussian? [bool]'],
 'fitplot': [False, 'Overplot profile fit?'],
 'fittype': ['Gaussian2D', 'Profile type to fit (Gaussian2D)'],
 'function': ['radial_profile'],
 'getdata': [False, 'print the plotted data values'],
 'magzero': [25.0, 'magnitude zero point'],
 'marker': ['o', 'The marker character to use, matplotlib style'],
 'pixels': [True, 'Plot all pixels at each radius? (False bins the data)'],
 'pointmode': [True, 'plot points instead of lines? [bool]'],
 'rplot': [8.0, 'Plotting radius in pixels'],
 'skyrad': [10.0, 'Background inner radius in pixels, from center of object'],
 'title': [None, 'Title of the plot'],
 'width': [5.0, 'Background annulus width in pixels'],
 'xlabel': ['Radius', 'The string for the xaxis label'],
 'ylabel': ['Flux', 'The string for the yaxis label']}

```
skyrad here is taken to the inside radius of the sky annulus, which according to the defaults will have a width of 5 pixels.  So from the center of the star, the sky background annulus starts at 10pixels and extends to 15 pixels. This is an image generated from the aperture photometry key, it shows the object, with the green circle centered, and the red sky annulus. This one had the skyrad at 15pixels from center with a width of 5 pixels.

![imexam_plot](https://user-images.githubusercontent.com/503615/38384922-71d3d34a-38de-11e8-9753-e67ecad8df79.png)

--------------
**RE: centering** 

IRAF iterates calculating the central moment of pixels around the source inside  rimexam.radius /2 until the answers agree.  `imexam` uses the center from a Gaussian2D fit by default. It uses photutils for any photometry measures. 

...looking at other differences in the radial plot now.....

**Comment by sosey** [comment]
I *think* that the values we are getting from `imexam` are reasonable, plus or minus the fractional pixel center of the source. I don't have the exact radius values from IRAF, but we can look at them from `imexam` explicitly and judge for ourselves. Here's the reasoning:

* using the center that @mackjenn  listed for the star to begin with: (x=462.44, y=377.04), we have this star:
![test_snap](https://user-images.githubusercontent.com/503615/38401046-7bd8d122-3921-11e8-8a5f-3ec41ebb8c44.png)

This is the pixel table around the brightest pixel, you can see they are varying quite a lot and the PSF is lopsided:
<img width="447" alt="pixtable" src="https://user-images.githubusercontent.com/503615/38430386-18f3492a-398f-11e8-9236-181ae9de619c.png">

We can get the list of radius and flux values for all pixels in this cutout from `imexam`:
```
from imexam.imexamine import Imexamine
from astropy.io import fits
image=fits.getdata('iacs01t4q_flt.fits', ext=1)
plots=Imexamine()  # setup the plotting control
plots.set_data(image)  # give it our data array 
x=462.44
y=377.04
radius, flux = plots.radial_profile(x,y,genplot=False)
xc=462.438784	yc=377.038866
```
These are the just the first few values, sorted in radius order.
No background subtraction has been done, so they are the 
pure pixel fluxes.  The radius here is just sqrt(x^2 + y^2) where 
x and y are the pixel from the center of the object, including the fractional center.
```
In [15]: radius
Out[15]: 
array([  0.44050167,   1.12772916,   1.12772916,   1.43930859,
         1.43930859,   1.77463815,   1.77463815,   1.77463815,
         1.77463815,   2.08554655,   2.08554655,   2.43909342,

In [16]: flux
Out[16]: 
array([ 408.87057495,  112.11755371,   91.90717316,  361.9876709 ,
         41.23228073,   64.6014328 ,   48.38606262,   76.15605927,
         92.4905777 ,   37.25744629,   41.94879532,    7.88528776,
```
![radial_frac_center](https://user-images.githubusercontent.com/503615/38401878-5a38e156-3926-11e8-8629-eac4ddf40b07.png)
So that second highest value comes up around 1.4 pixels, which jives with the `imexam` plot.
(The 'x' markers are from the overplot of the (radius, flux) arrays that I pulled above and the blue circles were created by the method radial_plot method ).

Compare to the radial plot from IRAF, it shows the radius at about 0.5 pixels less. 
Accounting for the zero-pixel offset in python, the integer centers from IRAF and `imexam` are identical. 

<img width="623" alt="iraf_radial" src="https://user-images.githubusercontent.com/503615/38401958-dc8905e6-3926-11e8-9f45-3e97dccf3155.png">

If I take away the fractional centers, and just calculate the radius from the floored pixel values, the results in `imexam` move closer to the 1 pixel radius IRAF shows for the flux we are looking at. Those fractional centers are somewhat variable for both IRAF and `imexam`. 

If I change my strategy a little and instead use the gauss center to guess at the data chunk center that I'm grabbing, and then search for the brightest pixel and use that as the center reference it gets a little closer to the IRAF plot:
![diff_center](https://user-images.githubusercontent.com/503615/38432519-b250a74c-3995-11e8-8f1f-d9731104e534.png)
The blue markers are with the brightest pixel center and the red with the gaussian fit center. 

My SPP is hella rusty, but I think this is part of the difference between IRAF and `imexam`. The final radius might also be shifted a little because I think that `IRAF.rimexam` is using `IRAF.psfmeasure` which  is subsampling pixels through `starfocus`. 

So - does this seem reasonable to you both? Shall I make the centering change to `imexam`? You'll still have the offset difference for the peak pixel because it's now the zero reference, instead of the calculated center. The IRAF plot appears to be centered on the gaussian fit to the data, and the radii seem to be computed from the integer brightest pixel. I still have to implement the fit overlay part in the `imexam` radial profile.

**Comment by Vb2341** [comment]
I've actually had to implement something similar for some science work, and I think the issue might be the centering (and therefore the distance computation).  I simply calculate the center of mass and measure the distances to each pixel center from the center of mass (within an 11x11 cutout).  I've used the same source you used in a quick test and  my result seems to match the pyraf result pretty well-

![image](https://user-images.githubusercontent.com/6558407/38576517-5c43207a-3ccc-11e8-8906-cddc189e613f.png)

The points are colored by some SNR-like quantity (which is then used as the weight in the fit of the gaussian), but thats pretty much something you can ignore.  The centroid I get, is basically the same : (462.39, 377.08).  The centers of each pixel are used as the integer positions (i.e. the center of the bottom left pixel would be (0,0) in the cutout.  the <.1 pix shift between the different centroids listed shouldn't make a difference I think.

**Comment by sosey** [comment]
yes, when I use the COM that iraf uses for the points I get the same thing, and I can match the centroid from iraf exactly with sigma clipping.  I know the differences between `imexam` and iraf at this point, the question is what is the better way to do it.  I have other fit updates on disk that I'm generalizing and will push shortly.  If you'd like to test the changes I'll ping you on the PR when I push! :smile:
