### ISSUE TITLE
automatically plotting surface plots from python script

### ISSUE THREAD

**Issue by FSBoyden** [spacetelescope/imexam#143]
Hi

I would like to automatically plot surface and contour plots of a specified section centred at predefined coordinates from a python script.

Reasoning: I would like to monitor in real time a stellar image from a live CCD feed (multi-exposure) as the fits files are displayed in ds9. I use xmccd lib to interface with Apogee CCD. It utilises ds9 to display the image data and saves the image to fits. A background script monitors the folder and as a new fits image is created runs a python script with imexam commands on the current image. I am able to scale and manage color and etc of the current image, but am unable to generate a surface plot and contour plot (as 2 separate windows) of the selected coordinates from the script.

Imaxime also has some issues using interactive commands during live image feed.

Please assist.

Regards
Pat van Heerden

**Comment by FSBoyden** [comment]
Hi Megan


The additional errors are sorted. My xauth/xhost permissions for DISPLAY was not set.


This also sorted the manual interactive plotting commands during live feed.


Thus: Back to the scripts:


The script that monitors "feed" from camera is just a .sh script:


#/code start

DIR=./
inotifywait -m -r -e create "$DIR" | while read f
do
    python colimage.py
done

#/code end


it runs colimage.py python script for each new image generated from the camera


colimage.py looks as follows:


#code start


import imexam
import os
import sys
import matplotlib

viewer=imexam.connect('ds9')         #connect to current active ds9
viewer.zoom('to fit')                            #reset zoom to fit view
viewer.scale('zscale')                            #scale image
viewer.scale('sqrt')                                #add scale image
viewer.cmap(color='heat')                #set cmap
viewer.panto_image(150,950)        #pan to section where ROI is
viewer.zoom(3)                                    #zoom in on ROI


#Additional code for plotting goes here

exit()
#code end


What I require is the following command sequence:

#code

#close active imexam() plot windows if any open


viewer.imexam()    #generate new instance

keystroke(e)     #contour plot of region at (150,950)

keystroke(2)    #pass next plot to new window

keystroke(w)    #surface plot of region at (150,950)


#end code


These events need to happen as "live" as possible. We need to collimate our 60inch telescope's primary mirror, and for that we need to actively monitor the out of focus stellar image shape (doughnut) for asymmetry while adjusting the mirror cell.


Your guidance is much appreciated

Thank you

Regards

Pat


[UFS Logo]
Dr. Hendrik Van Heerden
Sr Officer:ProfessionalServices*: Physics
Sr Bmpte:Vakk Dienste*: Fisika
Faculty / Fakulteit: Natural and Agricultural Sciences / Natuur- en Landbouwetenskappe
PO Box / Posbus 339, Bloemfontein 9300, Republic of South Africa / Republiek van Suid-Afrika
[http://apps.ufs.ac.za/emailsignature/siteimages/icon_tel.jpg] +27 (0)51 401 3509
[http://apps.ufs.ac.za/emailsignature/siteimages/icon_cel.jpg] +27 (0)72 996 3118
[http://apps.ufs.ac.za/emailsignature/siteimages/icon_fax.jpg] +27 (0)51 401 3507
[http://apps.ufs.ac.za/emailsignature/siteimages/icon_mail.jpg] VanHeerdenHJ@ufs.ac.za
[http://apps.ufs.ac.za/emailsignature/siteimages/icon_facebook.png]<http://www.facebook.com/home.php#%21/pages/University-of-the-Free-State/175257709184139> [http://apps.ufs.ac.za/emailsignature/siteimages/icon_twitter.png] <http://twitter.com/#%21/UFSweb>  [http://apps.ufs.ac.za/emailsignature/siteimages/icon_youtube.png] <http://www.youtube.com/UFSWeb>
[http://apps.ufs.ac.za/emailsignature/siteimages/inspire.jpg]   [http://apps.ufs.ac.za/emailsignature/siteimages/inspireer.jpg]
________________________________

**Comment by sosey** [comment]
Hi Pat,

Glad the display is working now.

For the plotting, I think the easiest way to go is to open a separate plotting instance. You can do this regardless of the imexam() object that you already have interacting with ds9. You can either retrieve the data into an array from the viewer object and then use it, or you can read it in from file. 

An example would be, starting with what you already have:
    
    import imexam
    import os
    import sys
    import matplotlib

    viewer=imexam.connect('ds9')         #connect to current active ds9

 If you wanted to load it with`imexam`, the command would be `viewer.load_fits(filename)`. Continuing on with your example:

    viewer.zoom('to fit')                     #reset zoom to fit view
    viewer.scale('zscale')                  #scale image
    viewer.scale('sqrt')                      #add scale image
    viewer.cmap(color='heat')          #set cmap
    viewer.panto_image(150,950)    #pan to section where ROI is
    viewer.zoom(3)                           #zoom in on ROI
    
If you want to grab the image data that is already displayed in the viewer:

    data = viewer.get_data()  # get the currently displayed frame data

If you want to load the data from a file on disk instead of directly from ds9:
    
    from astropy.io import fits
    data = fits.getdata(filename)

Now, you can make a separate plotting instance for displaying additional plots without destroying the ds9 instance that you're also using:

    from imexam.imexamine import Imexamine
    plotter = Imexamine()  # this object doesn't use a viewer, i.e. ds9

Now, you can either set the data that is always used for plotting:

    plotter.set_data(data)
    plotter.surface(150, 950)

Or, you can always pass the data array that you want plotted:

    plotter.surface(150, 950, data)

To focus a new window call `new_plot_window`. The specification of numbers to this method is a side effect of the api right now, the numbers don't matter here

    plotter.new_plot_window(0,0)  

Now you can make the next plot:

    plotter.contour(150, 950)  # if you used set_data
    plotter.contour(150, 950, data) # if you didn't 

you can close the plotting windows using

    plotter.close()

.... and continue on . If this makes sense for what you want, and it works let me know!  Otherwise we can try a different method. I can think a little harder about the fastest way to do the plot+update if this method proves slow for you as well. 

cheers
meg

**Comment by sosey** [comment]
ah yes, if you're just calling the script from the shell, as soon as the script terminates the windows will close.  The script didn't make it through, if you'd like you can send it directly to me at  sosey at stsci dot edu and I'll take a look. 

 The save works as you surmised, that command, `plotter.save("filename")` will save the current plot window to file, and it will be of the type specified in the extension of the filename, e.g.: plot.jpg  will be jpg, plot.pdf will be pdf...

Glad things are up and running! Feel free to open more issues if you have suggestions for improvements as well.
