### ISSUE TITLE
Build fail on Windows 

### ISSUE THREAD

**Issue by mwcraig** [spacetelescope/imexam#33]
On windows the xpa extension fails to build because it can't find the  header file `unistd.h` -- see https://ci.appveyor.com/project/mwcraig/conda-builder-affiliated/build/1.0.42/job/wf6r4vdc63thckyn#L552

Cursory googling turned up this, but haven't tried it: http://stackoverflow.com/questions/341817/is-there-a-replacement-for-unistd-h-for-windows-visual-c

**Comment by sosey** [comment]
Yah, it might be worth trying to add the process or io libraries for the windows build and try again.
XPA says that v2.1.15 should build under mingw, you could try switching the appveryor to use mingw instead of cygwin, it seems possible:

 http://help.appveyor.com/discussions/questions/372-build-setup-for-a-c-program 

will that jive with the other windows builds you're working on?

**Comment by mwcraig** [comment]
I'm going to close this -- in the long run the ginga backend is probably a better fit for Windows, and I couldn't get XPA to build.
