### ISSUE TITLE
Integrate with stginga?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/imexam#41]
I don't know how feasible this is, but since `stginga` (https://github.com/spacetelescope/stginga) uses Ginga and `imexam` has a Ginga viewer, maybe `stginga` can somehow have access to `imexam` or something...

p/s: "Assimilate!"

**Comment by sosey** [comment]
You should be able to do this with the imexam code as it's released right now, and it will open a ginga matplotlib window on your desktop and you can look at images

from imexam import ginga_viewer
window=ginga_viewer.ginga_mp()
window.load_fits('/Users/sosey/ibh719grq_flt.fits')

You have access to the imexam functions we've added as wrapper commands, plus the ginga keyboard keys, like hitting "." to rotate the image being viewed

you can also get info on the image,  window.get_header() will print the fits header to the terminal
or:

In [26]: window.get_viewer_info()
Out[26]: 
{1: {'extname': None,
  'extver': None,
  'filename': '/Users/sosey/ibh719grq_flt.fits',
  'hdu': <astropy.io.fits.hdu.image.ImageHDU at 0x10d2a5710>,
  'image': <ginga.AstroImage.AstroImage at 0x10d280c90>,
  'iscube': False,
  'mef': False,
  'naxis': 0,
  'numaxis': 2,
  'user_array': None}}

window.close() will shut everything down.

I think I got most of the notebook + mpl ginga window working at scipy, need to finish the qt and thread control stuff. you guys might be more ahead on that.  I haven't tried out the stginga stuff, I'll take a look when I get a chance...but that might not be until the new year

**Comment by pllim** [comment]
I am thinking more like enabling users to use `imexam` and our own custom plugins at the same time. Not sure if it is even possible, given that you have your own viewer implementation.

**Comment by sosey** [comment]
It depends on how you want the interaction to go between imexam and the plugins. Most of imexam is geared towards making plots of things and viewing images because it's meant for interactive image analysis. You can call the plots separately without invoking the DS9 or Ginga interface like in the example here: 

http://imexam.readthedocs.org/en/latest/imexam/examples.html#example-5

this will throw up a matplotlib plot, so if you want to take the data and make a plot in ginga some other way it would probably be best to code it yourself. 

I think these are two different interaction regimes we are talking about and might not be good to intermix them (for code clarity sake at least).  It sounds like you want to provide a wrapper interface into the ginga code which might be easier for scientist programmers to interact with, but still be inside the ginga enviroment, and maybe just build gui's that do things. 

I originally coded imexam to be lightweight, so that you could do the interactive image analysis, or send it data to make plots, or throw up quick image windows to check things if you wanted to include it in more complex code that was doing image analysis (for example choosing psf stars).  It's extensible so you can add your own image viewers, or attach your own analysis functions, but it's not designed as a gui building library like ginga. 

Does this help?

**Comment by sosey** [comment]
If there's a way to put a matplotlib plot window inside the ginga gui, then you could probably use the imexam functions in some way. You'll have to take a look at the ginga_viewer script  and the imexamine plotting functions to see if there's anything useful there for stginga

**Comment by pllim** [comment]
Let's just keep this open so we can revisit in the future.

**Comment by pllim** [comment]
I am moving this over to spacetelescope/stginga#69. Thanks for your feedback, @sosey!

**Comment by sosey** [comment]
@eteq related to our discussion

**Comment by pllim** [comment]
Huh? Is this reviving after 2 years?
