### ISSUE TITLE
connect without an argument raises an error

### ISSUE THREAD

**Issue by eteq** [spacetelescope/imexam#44]
I noticed a strange error when I follow the instructions for Example 1 at http://imexam.readthedocs.org/imexam/examples.html .  If I try to connect to ds9 via ``imexam.connect()`` without explicitly saying ``imexam.connect('ds9')`` (which is what Example 1 suggests is possible), I get a rather arcane error that I don't really understand.  I do suspect it has something to do with the ``# this might be sketchy`` line right above, though ;)

```
In [2]: import imexam
In [3]: viewer = imexam.connect()
/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.3.dev0-py3.5-macosx-10.5-x86_64.egg/imexam/ds9_viewer.py:554: UserWarning: Starting ds9 failed
  warnings.warn("Starting ds9 failed")
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-6f0574bcd0ef> in <module>()
----> 1 viewer = imexam.connect()

/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.3.dev0-py3.5-macosx-10.5-x86_64.egg/imexam/connect.py in __init__(self, target, path, viewer, wait_time, quit_window)
     80         if 'ds9' in self._viewer:
     81             self.window = ds9(
---> 82                 target=target, path=path, wait_time=wait_time, quit_ds9_on_del=quit_window)
     83             self._event_driven_exam = False  # use the imexam loop
     84 

/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.3.dev0-py3.5-macosx-10.5-x86_64.egg/imexam/ds9_viewer.py in __init__(self, target, path, wait_time, quit_ds9_on_del)
    198 
    199             elif 'local' in self._xpa_method:
--> 200                 self._xpa_name, self._ds9_unix_name = self._run_unixonly_ds9()
    201 
    202             # tells xpa where to find sockets

/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.3.dev0-py3.5-macosx-10.5-x86_64.egg/imexam/ds9_viewer.py in _run_unixonly_ds9(self)
    562         # this might be sketchy
    563         try:
--> 564             file_list.remove(".IMT")  # should be in the directory, if not
    565         except (ValueError, IOError):
    566             warnings.warn("IMT not found in tmp, using first thing in list")

UnboundLocalError: local variable 'file_list' referenced before assignment
```

**Comment by pllim** [comment]
I have no problem with this under Anaconda Python 2.7.11 and SAOImage DS9 v7.1.

**Comment by pllim** [comment]
@eteq , I can't really test it but can you see if #45 get you past the `UnboundLocalError` and hopefully give you some other more meaningful error to work with? Or better yet, fix the problem?

**Comment by eteq** [comment]
@pllim - hmm, OK, that leads to a completely different error as shown below.  That's definitely more relevant, but I still don't really understand the cause... In particular I don't understand what's different between this and ``imexam.connect('ds9')``...

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-f63b9047ba1c> in <module>()
----> 1 v=imexam.connect()

/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.2-py3.5-macosx-10.5-x86_64.egg/imexam/connect.py in __init__(self, target, path, viewer, wait_time, quit_window)
     80         if 'ds9' in self._viewer:
     81             self.window = ds9(
---> 82                 target=target, path=path, wait_time=wait_time, quit_ds9_on_del=quit_window)
     83             self._event_driven_exam = False  # use the imexam loop
     84 

/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.2-py3.5-macosx-10.5-x86_64.egg/imexam/ds9_viewer.py in __init__(self, target, path, wait_time, quit_ds9_on_del)
    198 
    199             elif 'local' in self._xpa_method:
--> 200                 self._xpa_name, self._ds9_unix_name = self._run_unixonly_ds9()
    201 
    202             # tells xpa where to find sockets

/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.2-py3.5-macosx-10.5-x86_64.egg/imexam/ds9_viewer.py in _run_unixonly_ds9(self)
    569             xpaname = os.path.join(self._tmpd_name, file_list[0])
    570         else:
--> 571             shutil.rmtree(self._tmpd_name)
    572             raise ValueError("Problem starting ds9 local socket connection")
    573 

/Users/erik/miniconda3/envs/imexam/lib/python3.5/shutil.py in rmtree(path, ignore_errors, onerror)
    486             os.close(fd)
    487     else:
--> 488         return _rmtree_unsafe(path, onerror)
    489 
    490 # Allow introspection of whether or not the hardening against symlink

/Users/erik/miniconda3/envs/imexam/lib/python3.5/shutil.py in _rmtree_unsafe(path, onerror)
    368         names = os.listdir(path)
    369     except OSError:
--> 370         onerror(os.listdir, path, sys.exc_info())
    371     for name in names:
    372         fullname = os.path.join(path, name)

/Users/erik/miniconda3/envs/imexam/lib/python3.5/shutil.py in _rmtree_unsafe(path, onerror)
    366     names = []
    367     try:
--> 368         names = os.listdir(path)
    369     except OSError:
    370         onerror(os.listdir, path, sys.exc_info())

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/xpa_erikhtwoxz0o'
```

**Comment by pllim** [comment]
@eteq , that is just `imexam` trying to delete a temporary directory that was never created. But if you are already in that `else` logic block, the next thing that will happen is this:

```python
raise ValueError("Problem starting ds9 local socket connection")
```

**Comment by pllim** [comment]
The difference between `connect()` (`target=None`) and `connect('ds9')` (`target='ds9'`) is this logic in `ds9_viewer.py`:

```python
        if not target:
            # Check to see if the user has chosen a preference first
            if 'XPA_METHOD' in os.environ:
                self._xpa_method = os.environ['XPA_METHOD'].lower()

            if 'inet' in self._xpa_method:
                self._xpa_name = self.run_inet_ds9()
                # xpa_name is the title of the window, the xpa can be referenced
                # with either the socket address or name of the window

            elif 'local' in self._xpa_method:
                self._xpa_name, self._ds9_unix_name = self._run_unixonly_ds9()

            # tells xpa where to find sockets
            os.environ['XPA_METHOD'] = self._xpa_method

        else:
            # just register with the target the user provided
            self._xpa_name = target
```

**Comment by eteq** [comment]
Ah, gotcha, so that explains why the error hits at `_run_unixonly_ds9`.  But I still don't understand what the purpose is of the temporary directory that gets created in that function...  I admit my understanding of XPA is at the level of "minimum necessary for what I need at any given moment", though...

**Comment by sosey** [comment]
It's been a while, and I try to expunge XPA memories because they hurt... but the XPA prefers to run sockets all of the same type. If you don't already have an instance of ds9 running, then it defaults down to the unix local socket, which are file references, this is the most secure I believe because you can limit access to the process by userid.  If the process doesn't start up and the local socket can't be found or connected to then the code tries to cleanup. So I don't create the directory but I can guess how it's named and try and clean it, but I should probably put a better check for existence in there.

If you start up ds9 with a local unix socket, go look in the File->XPA information  menu and you'll see the socket information, here's mine:

XPA_VERSION: 2.1.14
XPA_CLASS: DS9
XPA_NAME: 1454532149.02 (which is a random name imexam sent it)
XPA_METHOD: /tmp/xpa_soseyvxTSeb/DS9_1454532149.02.26690  --> the communication socket

@eteq you can try setting XPA_METHOD in your environment to inet, that might solve your issue for now. You can see the internet socket difference again in the XPA info menu where it shows up as number:number.

I'm not sure why your unix socket isn't being created yet.  What version of ds9 are you running? I'm using 7.1.  Are you able to get references to ds9 and xpans from imexam?:

import imexam
imexam.find_ds9()
imexam.find_xpans()

Another thing to try is setting the wait time longer and see if that helps:

a=imexam.connect(wait_time=10)  will increase to 10 seconds, which should be more than enough time to wait for the socket to establish.  You can also try giving it an explicit path to ds9:

a=imexam.connect(path="/my/ds9/location")


all said, the socket connection and listening are working under SSBDEV: 

In [4]: imexam.list_active_ds9()
DS9 megan gs /tmp/xpa/DS9_megan.26155 sosey

where "megan" is the name of a ds9 window I opened from the os command line.

The socket connection works in my conda env as well, but the listening is off even though xpans seems to exist, I'll look into that as a separate issue.

**Comment by eteq** [comment]
Hmm, we're closer but I'm still a bit confused, @sosey:  I tried as you suggested, and got a few interesting bits:

* `imexam.find_ds9` and `imexam.find_xpams` both work and find the right path
* `imexam.list_active_ds9` yields this:
```
/Users/erik/miniconda3/envs/imexam/lib/python3.5/site-packages/imexam-0.5.2-py3.5-macosx-10.5-x86_64.egg/imexam/util.py in list_active_ds9()
     54     if find_xpans():
     55         try:
---> 56             sessions = (xpa.get('xpans'))
     57             if len(sessions) < 1:
     58                 print("No active sessions")

wrappers/xpa.pyx in xpa.get (wrappers/xpa.c:1379)()

TypeError: expected bytes, str found
```
which looks to me to be a python 3.x incompatibility (I was testing this on anaconda 3.5.something).  

But if I switch to 2.7, it happily reports either ``No active sessions registered`` or if I've already started a ds9, it gets ``DS9 ds9 gs ac120a41:61597 erik``.  So that looks like it is indeed in 'inet' mode and successfully found `xpans`.

If I go ahead in 2.7 and then and do ``imexam.connect()``, I still get ``OSError: [Errno 2] No such file or directory: '/tmp/xpa_erikKdZwyU'``.  Am I right in concluding that's because it thinks I'm in local socket and not inet mode?  So in principal the solution is just to try to get the no-argument version of ``imexam.connect()`` to also try the inet way?

**Comment by sosey** [comment]
Yes, that' a compatibility thing  I still need to fix. I had to blow away my environments yesturday for some calwf3 testing so I'm a little behind but will try and get to that next (after I fix the travis issues)

It may be because it thinks you're in local mode. Did you try setting in your env XPA_METHOD = inet?  That should make imexam skip that section all together. Try that and I'll see where the logic issue is that's making it think it still needs to start or clean a local session.

**Comment by eteq** [comment]
Aha - I did `XPA_METHOD=inet` when starting `ds9`, not when starting `python`.  When I do ``XPA_METHOD=inet ipython``, it *does* try to start up ds9.  However, I get a different error now, with the traceback below.  I *think* this error is happening because I have a rather arcane way of calling ds9 (the `ds9` it finds is actually a shell script to go and find the right version of ds9 on my machine...), but I think the fact that `p` doesn't exist might be a real error?

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-1-fd029befc726> in <module>()
----> 1 import imexam;v=imexam.connect()

/Users/erik/miniconda3/envs/imexam2/lib/python2.7/site-packages/imexam-0.5.2-py2.7-macosx-10.5-x86_64.egg/imexam/connect.pyc in __init__(self, target, path, viewer, wait_time, quit_window)
     80         if 'ds9' in self._viewer:
     81             self.window = ds9(
---> 82                 target=target, path=path, wait_time=wait_time, quit_ds9_on_del=quit_window)
     83             self._event_driven_exam = False  # use the imexam loop
     84 

/Users/erik/miniconda3/envs/imexam2/lib/python2.7/site-packages/imexam-0.5.2-py2.7-macosx-10.5-x86_64.egg/imexam/ds9_viewer.py in __init__(self, target, path, wait_time, quit_ds9_on_del)
    193 
    194             if 'inet' in self._xpa_method:
--> 195                 self._xpa_name = self.run_inet_ds9()
    196                 # xpa_name is the title of the window, the xpa can be referenced
    197                 # with either the socket address or name of the window

/Users/erik/miniconda3/envs/imexam2/lib/python2.7/site-packages/imexam-0.5.2-py2.7-macosx-10.5-x86_64.egg/imexam/ds9_viewer.py in run_inet_ds9(self)
    497             print("Exception: {}".format(repr(e)))
    498             from signal import SIGTERM
--> 499             os.kill(p.pid, SIGTERM)
    500             raise
    501 

UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by sosey** [comment]
well that's a new one. Yah I'll look at the process thing. 

So, try this:
set your OS env,  export XPA_METHOD=inet, 
start python 
import imexam

Since you have a special place you want to grab ds9 from, and its scripts, lets just give that location to imexam and see if that at least gets a smooth start for you?

a=imexam.connect(path = "my special ds9 path")

**Comment by eteq** [comment]
@sosey - tried what you said here and I got the exact same result as the traceback I posted above.  *But*, I think I figured it out:

If I do what I *originally* did (``connect()`` without the path), and use the debugger to try to *create* the `Popen` in `run_inet_ds9`, it fails because of ``OSError: OSError(8, 'Exec format error')``. This is probably because the `ds9` on my path is actually a file that just contains the line ``/Applications/SAOImage\ DS9.app/Contents/MacOS/ds9 "$@"`` (That was a necessary hack for some reason, although I don't remember why...).

If I add ``#!/bin/sh`` to the top of that file... It works!  So the only real underlying problem was that the ``ds9`` on my path was an executable without a proper hashbang to tell it what to do.

There's still the *proximate* error in the traceback not passing on that error, though.  I'll issue a PR to fix that as I think I see the problem.  Once that's in along with #45 I think this can be closed.
